FROM golang:1.21.6-alpine

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY .  .

RUN GOENV=/app/go.env  go build -mod vendor /app/cmd/core-module/ 

EXPOSE 8080

ENTRYPOINT exec go run cmd/core-module/main.go --config=cmd/core-module/config.json