version: '3.4'

services:
  client:
    image: grpc-client
    build:
      context: .
      dockerfile: Dockerfile_base
    ports:
      - "8080:8080"
    networks:
      - awesome
    depends_on:
      - server
  server:
    image: grpc-server
    build:
      context: .
      dockerfile: Dockerfile_core
    ports:
      - "9000:9000"
    networks:
      - awesome
networks:
  awesome: