FROM golang:1.21.6-alpine

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN GOENV=/app/go.env go build -C /app/cmd/base-module/

EXPOSE 8080

ENTRYPOINT exec go run cmd/core-module/main.go --config=cmd/core-module --configFile=docker_config