version: '3.4'

services:
  client:
    container_name: grpc-client
    image: grpc-client
    build:
      context: .
      dockerfile: Dockerfile_base
    ports:
      - "8080:8080"
    networks:
      - awesome
    depends_on:
      - server
  server:
    container_name: grpc-server
    image: grpc-server
    build:
      context: .
      dockerfile: Dockerfile_core
    ports:
      - "9005:9000"
    networks:
      - awesome
    restart: unless-stopped
networks:
  awesome: